services:
  # Backend API
  - type: web
    name: swift-standalone-api
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: swift-standalone-db
          property: connectionString
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  # Frontend Static Site
  - type: web
    name: swift-standalone-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && VITE_API_URL=$VITE_API_URL npm run build"
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false

# Database
databases:
  - name: swift-standalone-db
    databaseName: swift_standalone
    user: swift_user
    plan: free
